import { Router } from "express";
import { create, edit, getAll, remove, get } from "../controllers/hotel.controller.js";
import { verifyToken } from "../utils/auth.js";
const router = Router();
router.put("/:id", verifyToken, edit);
router.delete("/:id", verifyToken, remove);
router.get("/:id", get);
router.get("/", getAll);
router.post("/", verifyToken, create);
export default router;