import { Router } from "express";
import { create, edit, getAll, remove, get } from "../controllers/hotel.controller.js";
import { verifyAdmin } from "../utils/auth.js";
const router = Router();
router.put("/:id", verifyAdmin, edit);
router.delete("/:id", verifyAdmin, remove);
router.get("/:id", get);
router.get("/", getAll);
router.post("/", verifyAdmin, create);
export default router;